GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/users/1

###

GET http://localhost:3001/api/users/1?read=true


### 
GET http://localhost:3001/api/users/me
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbGxlQGV4YW1wbGUuY29tIiwibmFtZSI6IlZpbGxlIiwiaWQiOjEsImRpc2FibGVkIjpmYWxzZSwiaWF0IjoxNjQxNzU1NTEwfQ.XabjNy6bMsyJ9phq0zpl5MPncRdka3vN2issCAg4DF4

