POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbGxlIiwibmFtZSI6IlZpbGxlIiwiaWQiOjEsImlhdCI6MTY0MTU3ODYxMX0.Yl_2GE0ZxmOv8UyQnD_iPZ-Zpf-ygopJOSA4kQ9ONnQ

{
  "author": "Sensei Luukkainen",
  "title": "Senseis wisdom, part2",
  "url": "http://sensei2.codecache.eu",
  "likes": 10
}

###

POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbGxlMkBleGFtcGxlLmNvbSIsIm5hbWUiOiJWaWxsZSIsImlkIjoyLCJkaXNhYmxlZCI6ZmFsc2UsImlhdCI6MTY0MTc1NTI5NH0.Rmc4RslStQBbb6rwVxlAwYGGl4WhywKXcfkft9JVDFs

{
  "author": "Pekka Päkä",
  "title": "Pekan horinat! osa2",
  "url": "http://pekka2.codecache.eu",
  "year": 2021
}
