POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbGxlIiwibmFtZSI6IlZpbGxlIiwiaWQiOjEsImlhdCI6MTY0MTU3ODYxMX0.Yl_2GE0ZxmOv8UyQnD_iPZ-Zpf-ygopJOSA4kQ9ONnQ

{
  "author": "Sensei Luukkainen",
  "title": "Senseis wisdom, part3",
  "url": "http://sensei3.codecache.eu",
  "likes": 2
}

###

POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbGxlQGV4YW1wbGUuY29tIiwibmFtZSI6IlZpbGxlIiwiaWQiOjEsImlhdCI6MTY0MTY2Nzg5NH0.6y9pJlipDjPRbQ68mQTCgqyxOyxA4SSHX_pDPK7Bzgo

{
  "author": "Pekka Päkä",
  "title": "Pekan horinat!",
  "url": "http://pekka.codecache.eu",
  "year": 2022
}
